specVersion: 0.2.0
name: subqueryHelloWorld
version: 1.0.0
description: Hero Module 1 task
repository: git@github.com:MercurySolar/subqueryHelloWorld.git
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xf22b7850cdd5a7657bbfd90ac86441275bbc57ace3d2698a740c7b0ec4de5ec3'
  endpoint: wss://pioneer-api.mercury-nodes.net
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler
